name = "ReparametrizableDistributions"
uuid = "7d03e222-df96-4b80-bcdc-d089be88b5f2"
authors = ["Nikolas Siccha <nikolas.siccha@aalto.fi>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
WarmupHMC = "60658175-6863-4866-a322-ab51a11c0cfe"
